markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Jsvisa's Blog
description: Jsvisa's blog. Powered by Jekyll
keywords: Share Learning
# url: http://local
feed: /atom.xml
favicon: /images/me.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于本站
    url: /about.html
  - text: 友情链接
    url: /links.html

production_url : http://username.github.io

#Author config
author:
    name: Jsvisa
    email: delweng@gmail.com
    imageLink: /images/me.png
    simpleIntro: 一个不会拼音的程序员
    detailIntro:
      <p>这是一个使用Jekyll搭建的个人博客, 这是一个记录个人学习工作经历的站点.</p>
      <p>本站点使用了<a href="https://github.com/pizn">掌心同学</a>提供的模板, 如果你也喜欢这个模板,
      可以访问<a href="https://github.com/pizn">掌心的github</a>获得.
      </p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-envelope
    url: mailto:delweng@gmail.com
  - class: icon-github
    url: http://github.com/jsvisa
  - class: icon-weibo
    url: http://weibo.com/u/1839426822
  - class: icon-twitter
    url: http://twitter.com/jsvisa
  - class: icon-google-plus
    url: http://plus.google.com

#Links
customLinks:
  - item:
    - text: 酷壳
      url: http://coolshell.cn/
    - text: 伯乐在线
      url: http://www.jobbole.com/
    - text: 何登成的技术博客
      url: http://hedengcheng.com/
    - text: Vimer的程序世界
      url: http://www.vimer.cn/
    message: 技术博客
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Jsvisa_Water的博客
      url: http://blog.csdn.net/june_water
    - text: Linux资料
      url: http://blog.csdn.net/hejianhua/article/category/718084
    - text: Vimer Scripts
      url: http://vim-scripts.org/vim/scripts.html
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-46308858-1

#comment config
disqus:
  config: false
  id: jsvisa

duoshuo:
  config: true
  id: jsvisa
