markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: June's Blog
description: June's blog.Powered by Jekyll
keywords: June Linux
url: http://junewater.github.io
feed: /atom.xml
favicon: /images/june.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于本站
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: June
    email: junevimer@gmail.com
    imageLink: /images/june.jpg
    simpleIntro: A coding farmer and vimer from Zhejiang University of Technology Hangzhou,China.
    detailIntro:
      <p>这是一个使用Jekyll搭建的个人博客</p>
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>
      <p>使用 Jekyll 来写博客，可以很简单，写 Markdown 就好。然而，Jekyll 还很年轻，没有很多主题的支持。这里的主题，就是为 Jekyll 而写的。希望你能喜欢.</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-envelope
    url: mailto:junevimer@gmail.com
  - class: icon-github
    url: http://github.com/junewater
  - class: icon-weibo
    url: http://weibo.com/junevimer
  - class: icon-twitter
    url: http://twitter.com
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 酷壳
      url: http://coolshell.cn/
    - text: 伯乐在线
      url: http://www.jobbole.com/
    - text: 何登成的技术博客
      url: http://hedengcheng.com/
    - text: Vimer的程序世界
      url: http://www.vimer.cn/
    message: 技术博客
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: June_Water的博客
      url: http://blog.csdn.net/june_water
    - text: Linux资料
      url: http://blog.csdn.net/hejianhua/article/category/718084
    - text: Vimer Scripts
      url: http://vim-scripts.org/vim/scripts.html
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-46308858-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: Junevimer
