markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Jsvisa's Blog
description: Jsvisa's blog. Powered by Jekyll
keywords: Share Learning
# url: http://local
feed: /atom.xml
favicon: /images/me.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于本站
    url: /about.html
  - text: 友情链接
    url: /links.html

production_url : http://username.github.io

#Author config
author:
    name: Jsvisa
    email: delweng@gmail.com
    imageLink: /images/me.png
    simpleIntro: 尽力而为
    detailIntro:
      <p>这是一个使用Jekyll搭建的个人博客, 这是一个记录个人学习工作经历的站点.</p>
      <p>本站点使用了<a href="https://github.com/pizn">掌心同学</a>提供的模板, 如果你也喜欢这个模板,
      可以访问<a href="https://github.com/pizn">掌心的github</a>获得.
      </p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-envelope
    url: mailto:delweng@gmail.com
  - class: icon-github
    url: http://github.com/jsvisa
  - class: icon-weibo
    url: http://weibo.com/u/1839426822
  - class: icon-twitter
    url: http://twitter.com/jsvisa
  - class: icon-google-plus
    url: http://plus.google.com

#Links
customLinks:
  - item:
    - text: 极客公园
      url: http://www.geekpark.net
    - text: GeekFan-Raspberry
      url: http://www.geekfan.net/category/hardware/raspberry-pi-hardware/
    message: 智能硬件
  - item:
    - text: 酷壳
      url: http://coolshell.cn/
    - text: 伯乐在线
      url: http://www.jobbole.com/
    - text: HackNews
      url: https://news.ycombinator.com
    - text: Startup News
      url: http://news.dbanotes.net/
    - text: 何登成的技术博客
      url: http://hedengcheng.com/
    - text: Vimer的程序世界
      url: http://www.vimer.cn/
    - text: GitGuy
      url: http://www.gitguys.com/topics/
    - text: 阮一峰的网络日志
      url: http://www.ruanyifeng.com/blog/
    message: 技术博客
  - item:
    - text: Rails 实战圣经
      url: http://ihower.tw/rails3/index.html
    - text: Ruby on Rails 教程
      url: http://railstutorial-china.org
    - text: HappyCast
      url: http://happycasts.net
    - text: JavaScript 标准教程
      url: http://javascript.ruanyifeng.com/
    message: 技术教程
  - item:
    - text: rubular
      url: http://rubular.com/
    - text: img2txt(ascii字符画)
      url: http://www.cssha.com/img2txt/
    - text: pdf2mobi
      url: http://www.pdf4kindle.com/
    message: 工具类
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Vimer Scripts
      url: http://vim-scripts.org/vim/scripts.html
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-46308858-1

#comment config
disqus:
  config: false
  id: jsvisa

duoshuo:
  config: true
  id: jsvisa
